import Head from 'next/head';
import { Container } from '@chakra-ui/react';
import Intro from '../components/sections/Intro';
import Popular from '../components/sections/popular';
import Services from '../components/sections/services';
import AboutUs from '../components/sections/about';
import Menus from '../components/sections/menus';

export default function Home() {
  return (
    <Container maxWidth={'100%'} p='0'>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Intro></Intro>
      <Popular></Popular>
      <Services></Services>
      <AboutUs></AboutUs>
      <Menus></Menus>
    </Container>
  );
}
